#!/usr/bin/env zsh

alias rm='echo "DELETE BLOCKED"'
alias shred='echo "DELETE BLOCKED"'
alias tetris=yetris
alias pacman=myman
alias py='python -q'
alias av='source .venv/bin/activate'
alias ez='nvim ~/dotfiles/.zsh'
alias sz='source ~/dotfiles/.zshrc'
alias on='nvim ~/dotfiles/.config/nvim'
alias n=nvim
alias code="open -a \"Visual Studio Code\" \."
alias ls=eza
alias cat=bat
alias top=htop
alias find=fd
alias grep=rg
alias nosleep="sudo pmset -a disablesleep 1"
alias yessleep="sudo pmset -a disablesleep 0"
alias ":q!"=exit

alias fact="$HOME/factor/factor"
alias gfact="$HOME/factor/Factor.app/Contents/MacOS/factor"
alias clj="cd $HOME/dummy_project/; lein repl"

bad_repls=("sbcl" "io")
for i in ${bad_repls[@]}; do
        alias $i="rlwrap $i"
done

ungate() {
        sudo codesign --force --deep --sign - "$1" && sudo xattr -cr "$1"
}
hf() {
        history -n 1 | tac | awk '!x[$0]++' | fzf --no-sort
}
bf() {
        brew list | fzf
}
lf() {
        ls -la | fzf
}
cf() {
        export MANPAGER="bat -plman --theme=light --color=always"
        whence -wm '*' | sed 's/:[^:]*$//' | grep -v "^_" | fzf --preview "tldr {} --color=always 2>/dev/null || man {} 2>/dev/null || which {}"
        export MANPAGER="nvim"
}
