#!/usr/bin/env zsh

pushd ~/dotfiles &>/dev/null
brew bundle dump --force --file="packages/brewfile" &>/dev/null
sed -i '' '/^#/d' packages/brewfile
pip list --not-required --format=freeze > packages/requirements.txt
git add packages/brewfile packages/requirements.txt
git commit
git push
popd &>/dev/null
